const actionTypes = {
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  LOAD_COURSES: "LOAD_COURSE",
  GET_AUTHORS: "GET_AUTHORS",
  DELETE_COURSE: "DELETE_COURSE",
  ALERT_RESPONSE: "ALERT_RESPONSE",
};
export default actionTypes;
